services:
  caddy:
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
    expose:
      - "8000"

volumes:
  caddy_data:
  caddy_config:
