services:
  traefik:
    image: traefik:v3.1
    command: 
      - "--log.level=DEBUG"
      - "--api.insecure=true" 
      - "--providers.docker=true"
      - "--providers.docker.network=traefik_network"
      - "--providers.docker.exposedbydefault=false"
      - "--metrics.prometheus=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      # - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      # - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=mixmyxxe@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    environment:
      - CF_API_EMAIL=mixmyxxe@gmail.com
      - CF_DNS_API_TOKEN=_5Pqr1G3zDjTW9VuEusQRDTV0VoXOLXqmc5azvbk
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      - traefik_network

  api:
    image: ghcr.io/drifterz13/nest-vultr-deploy:latest    
    environment:
      - PORT=8000
      - DATABASE_URL=file:/app/db/prod.db
    expose:
      - "8000"
    volumes:
      - db_data:/app/db
      - api_logs:/app/log
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.drifterz13.com`)"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"

volumes:
  db_data:
  api_logs:
    external: true
networks:
  traefik_network:
    external: true
