services:
  traefik:
    image: traefik:v3.1
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - "--api.insecure=true" 
      - "--providers.docker"
      - "--providers.docker.network=traefik_network"
      - "--metrics.prometheus=true" 
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik_network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.api.rule=Host(`api.docker.localhost`)"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
    environment:
      - PORT=8000
      - DATABASE_URL=file:/app/db/dev.db
    expose:
      - "8000"
    volumes:
      - db_data:/app/db
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true

volumes:
  db_data:

