services:
  caddy:
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8000
      - DATABASE_URL=file:/app/db/dev.db
    expose:
      - "8000"
    volumes:
      - sqlite_data:/app/db

volumes:
  caddy_data:
  caddy_config:
  sqlite_data:
