name: Deploy to VPS

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the latest code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build and push Docker image
    - name: Build and push Docker image
      run: |
        docker build -t drifterz13/nest-vultr-deploy:${{ github.sha }} -f Dockerfile.prod .
        docker push drifterz13/nest-vultr-deploy:${{ github.sha }}
        
    # 4. SSH into the VPS
    - name: SSH to VPS, deploy, and health check
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        script: |
          cd ~/nest-vultr-deploy
          git pull origin main
          export IMAGE_TAG=${{ github.sha }}

          docker compose -f compose.prod.yml pull
          docker compose -f compose.prod.yml down
          docker compose -f compose.prod.yml up -d --build
          docker image prune -af
